name: akm
version: 1.0.0+1
publish_to: none
description: Mobile app untuk Analisis Kredit Mikro built with Flutter and NodeJS.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  awesome_dialog: ^3.0.1
  cupertino_icons: ^1.0.5
  currency_text_input_formatter: ^2.1.7
  data_table_2: ^2.3.7
  double_back_to_close_app: ^2.1.0
  empty_widget: ^0.0.5
  extended_masked_text: ^2.3.1
  faker_dart: ^0.1.8
  fancy_shimmer_image: ^2.0.2
  file_picker: ^4.6.1
  filter_list: ^1.0.2
  finance:
    git:
      url: https://github.com/yuvaraja2303/finance/
      ref: patch-1
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.0.0
  flutter_form_builder: ^7.6.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.12
  flutter_native_splash: ^2.2.9
  flutter_styled_toast: ^2.1.3
  flutter_svg: ^1.1.5
  flutter_tex_js: ^1.2.17
  font_awesome_flutter: ^10.2.1
  form_builder_extra_fields: ^8.3.0
  form_builder_file_picker: ^2.3.0
  form_builder_image_picker: ^3.1.0
  form_builder_phone_field: ^1.3.0
  form_builder_validators: ^8.3.0
  geolocator: ^9.0.1
  get:
    git:
      url: https://github.com/jonataslaw/getx
      ref: master
  gif_view: ^0.1.1
  google_fonts: ^3.0.1
  http: ^0.13.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  just_the_tooltip: ^0.0.12
  liquid_progress_indicator: ^0.4.0
  loading_animation_widget: ^1.2.0+3
  material_design_icons_flutter: ^5.0.6996
  modal_bottom_sheet: ^2.1.2
  nekos: ^0.0.7
  open_file: ^3.2.1
  open_street_map_search_and_pick: ^0.0.11
  path_provider: ^2.0.11
  pdf: ^3.8.3
  printing: ^5.9.3
  responsive_framework:
    git:
      url: https://github.com/Codelessly/ResponsiveFramework
      ref: master
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  slide_digital_clock: ^1.0.2
  stepper_page_view: ^0.0.2
  terbilang_id: ^0.1.0
  unsplash_client: ^2.1.0+3
  vector_math: null
  wave: ^0.2.2

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: 2.0.1
  import_sorter: 
   git:
      url: https://github.com/gupta-shrinath/import_sorter
      ref: master

flutter:
  uses-material-design: true
  assets:
    - assets/images/search_section/
    - assets/images/splash_side/
    - assets/images/fixed_nonfixed/
    - assets/images/home/
    - assets/images/splash_screen/
    - assets/images/upload/
    - assets/images/approve/
    - assets/images/success_screen/
    - assets/images/agunan/
    - assets/images/business/
    - assets/images/karakter/
    - assets/images/keuangan_analisis/
    - assets/images/pdf/
    - assets/images/debitur_real/
    - assets/images/input_keuangan/
    - assets/fonts/times-new-roman.ttf
    - assets/fonts/times-new-roman-bold.ttf
    - assets/fonts/times-new-roman-italic.ttf
    - assets/fonts/times-new-roman-bold-italic.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/anya.png"

flutter_native_splash:
  background_image: "assets/images/splash_screen/background.png"
  image: "assets/images/splash_screen/splash_icon.png"
  branding: "assets/images/splash_screen/branding.png"

android_12:
  image: "assets/images/splash_screen/splash_icon.png"

dependency_overrides:
  intl: ^0.17.0
