name: akm
version: 1.1.16+34
publish_to: none
description: Mobile app untuk Analisis Kredit Mikro built with Flutter and NodeJS.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  about: ^2.1.1
  awesome_dialog: ^3.0.2
  bottom_bar_matu: ^1.3.0
  bootstrap_alert: ^1.0.1
  cached_network_image: ^3.2.3
  collection: 1.17.0
  cupertino_icons: ^1.0.5
  currency_text_input_formatter: ^2.1.9
  data_connection_checker:
    git:
      url: https://github.com/chornthorn/data_connection_checker.git
      ref: master
  data_table_2: ^2.4.1
  device_info_plus: ^8.1.0
  dio: ^5.0.3
  double_back_to_close_app: ^2.1.0
  extended_masked_text: ^2.3.1
  faker_dart: ^0.1.11
  finance:
    git:
      url: https://github.com/yuvaraja2303/finance/
      ref: patch-1
  firebase_analytics: ^10.1.6
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_crashlytics: ^3.0.17
  firebase_messaging: ^14.3.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_cached_pdfview:
    git:
      url: https://github.com/ewilliams-zoot/flutter_cached_pdfview/
      ref: patch-1
  flutter_custom_clippers: ^2.1.0
  flutter_echarts: ^2.4.0
  flutter_form_builder: ^7.8.0
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^3.1.0
  flutter_map_marker_popup: ^4.0.1
  flutter_markdown: ^0.6.13+1
  flutter_native_splash: ^2.2.19
  flutter_slidable: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_styled_toast: ^2.1.3
  flutter_svg: ^2.0.0+1
  flutter_tex_js: ^1.2.17
  font_awesome_flutter: ^10.4.0
  form_builder_extra_fields: ^8.5.0
  form_builder_file_picker:
    git:
      url: https://github.com/flutter-form-builder-ecosystem/form_builder_file_picker
      ref: main
  form_builder_image_picker: ^3.1.0
  form_builder_validators: ^8.5.0
  gallery_saver: ^2.3.2
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: 4.6.5
  getwidget: ^3.0.1
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.2
  http: ^0.13.5
  image_picker: ^0.8.7
  in_app_update:
    git:
      url: https://github.com/fleoparra/flutter_in_app_update
      ref: master
  intl: ^0.18.0
  introduction_screen:
    git:
      url: https://github.com/Pyozer/introduction_screen
      ref: master
  latlong2: ^0.8.1
  lottie: ^2.3.0
  map_launcher: ^2.5.0+1
  modal_bottom_sheet:
    git:
      url: https://github.com/jamesblasco/modal_bottom_sheet
      path: modal_bottom_sheet
      ref: main
  ntp: ^2.0.0
  numerus: ^2.0.0
  open_filex: ^4.3.2
  open_street_map_search_and_pick: ^0.0.16
  path_provider: ^2.0.14
  pdf: ^3.9.0
  photo_view: ^0.14.0
  printing: ^5.10.1
  random_avatar: ^0.0.8
  responsive_framework:
    git:
      url: https://github.com/Codelessly/ResponsiveFramework
      ref: master
  rive: 0.9.1
  scaffold_gradient_background: ^1.0.3+1
  settings_ui: ^2.0.2
  share_plus: ^6.3.1
  shared_preferences: ^2.0.20
  syncfusion_flutter_charts: ^21.1.35
  terbilang_id: ^0.1.0
  timeline_tile: ^2.0.0
  url_launcher: ^6.1.10
  vector_math: null
  wave: ^0.2.2
  webfeed:
    git:
      url: https://github.com/arhamcode/webfeed
      ref: master

dev_dependencies:
  change_app_package_name: ^1.1.0
  dart_code_metrics: ^5.7.0
  dependency_validator: ^3.2.2
  flutter_launcher_icons:
    git:
      url: https://github.com/carloshpb/flutter_launcher_icons
      ref: upgrade-image-4.0.10
  flutter_lints: 2.0.1
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/search_section/
    - assets/images/splash_side/
    - assets/images/home/
    - assets/images/splash_screen/
    - assets/images/pdf/
    - assets/images/menu_grid/
    - assets/fonts/times-new-roman.ttf
    - assets/fonts/times-new-roman-bold.ttf
    - assets/fonts/times-new-roman-italic.ttf
    - assets/fonts/times-new-roman-bold-italic.ttf
    - ABOUT.md
    - LICENSE.md
    - CHANGELOG.md
    - CONTRIBUTING.md
    - CODE_OF_CONDUCT.md

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/home/fleetime.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0e44c2"
  adaptive_icon_foreground: "assets/images/home/fleetime.png"

flutter_native_splash:
  background_image: "assets/images/splash_screen/background.png"
  image: "assets/images/splash_screen/splash_icon.png"
  branding: "assets/images/splash_screen/branding.png"

  android_12:
    image: "assets/images/splash_screen/fleetime_splash.png"
    color: "#42a5f5"
    icon_background_color: "#0e44c2"

  web: false
  fullscreen: true

dependency_overrides:
  intl: ^0.18.0
  markdown: ^6.0.1
